name: Deploy to GCP Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: lineappstest  # あなたのGCPプロジェクトIDに置き換えてください

    - name: Deploy to Cloud Storage
      run: |
        gsutil -m rsync -r ./ gs://reizi_line_test
